### ISSUE TITLE
Death Penalty even if Disabled still Penalizes the Player

### ISSUE THREAD

**Issue by LeDemmers** [Foghrye4/Iblis#21]
Config Option:

```
    # No death penalty to all skills and characteristics. [default: true]
    B:no_death_penalty=true
```

Doesn't work on a server. When users die, all of their skills are reset. Back to 0.

**Comment by Foghrye4** [comment]
I wasn't able to reproduce that on my localhost server.
1. Is this bug is reproduceable every time?
Try to use `/setattribute iblis.jumping 10`, kill yourself and respawn to get a quick result.
2. Is this bug caused by other mods interaction?
Try to remove all mods, except Iblis, and run a check.
3. Could be a certain Forge version handle things differently. What Forge version do you use?
4. If possible, provide a debug log from a moment of player death to a moment when he respawned. It could contain valuable info.

**Comment by LeDemmers** [comment]
I believe the mod PlayerRevive is interfering. Would it be possible to add support, as per don't penalize unless they user respawns? Not sure, I'll check when I get off work.

**Comment by Foghrye4** [comment]
Nope, not a PlayerRevive. Everything still works fine even with PlayerRevive installed.

**Comment by LeDemmers** [comment]
Mod is a branch called HardcoreRevival, might switch to PlayerRevive
